# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            learn. Just learn. Period
tagline:          Lakshmana Prabhu Venkatesan @ lakshmanav | Coder, Blogger
url:              
paginate:         1
baseurl:          /
author:
  name:           Lakshmana Prabhu Venkatesan
  url:            http://lakshmanav.github.io/
  email:          

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/lakshmanav/

pages_list:       {'Archive':'/archive'}
