# Dependencies
markdown:         pandoc
pandoc:
  extensions:
    - pipe_tables
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Lakshmana Prabhu Venkatesan @ lakshmanav | Coder, Blogger
tagline:          
url:              
paginate:         1
baseurl:          /
author:
  name:           Lakshmana Prabhu Venkatesan
  url:            http://lakshmanav.github.io/
  email:          

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/lakshmanav/

pages_list:       {'Archive':'/archive'}
